#include <errno.h>

int errno;

char *sys_errlist[] = {
  "not defined",
  "function number invarid",
  "file not found",
  "path not found",
  "too many open files (no handles avalable)",
  "access denied",
  "invalid handle",
  "memory controll block destroyed",
  "insufficient memory",
  "memory block address invalid",
  "environment invalid",
  "format invalid",
  "access code invalid",
  "data invalid",
  "",
  "invalid drive",

  "attempted to remove current directory",
  "not same device",
  "not more files",
  "disk write-protected",
  "unknown unit",
  "drive not ready",
  "unknown command",
  "data error",
  "bad request structure length",
  "seek error",
  "unknown media type (non-DOS disk)",
  "sector not found",
  "printer out of paper",
  "write fault",
  "read fault",
  "general failure",

  "sharing violation",
  "lock violation",
  "disk change invalid",
  "FCB unavailable",
  "sharing buffer overflow",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",

  "",
  "",
  "Network request not supported (DOS 3.1 + MS Networks)",
  "Remote Computer not listening",
  "Duplicate name on network",
  "Network name not found",
  "Network busy",
  "Network device no longer exists",
  "Network BIOS command limit exceeded",
  "Network adapter hardware error",
  "Incorrect response from network",
  "Unexpected network error",
  "Incompatible remote adapter",
  "Print queue full",
  "Queue not full",
  "Not enough space to print file",

  "Network name was deleted",
  "Network: access denied",
  "Network device type incorrect",
  "Network name not found",
  "Network name limit exceeded",
  "Network BIOS session limit exceeded",
  "Temporarily paused",
  "Network request not accepted",
  "Print/disk redirection paused (DOS 3.1 + MS Networks)",
  "",
  "",
  "",
  "",
  "",
  "",
  "",

  "file exists",
  "",
  "cannot make directory",
  "fail on INT 24h",
  "(DOS 3.3+) too many redirections",
  "(DOS 3.3+) duplicate redirection",
  "(DOS 3.3+) invalid password",
  "(DOS 3.3+) invalid parameter",
  "(DOS 3.3+) network write fault",
};

int  sys_nerr = 0x59;
